name: C/C++ CI

on:
  push:
    branches: [ "Lab5" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Lab3/590MakefileLab

    steps:
    - uses: actions/checkout@v4

    - name: Build program
      run: make

    - name: Run program
      run: make run

    - name: Run unit tests
      run: make test
