name: C/C++ CI

on:
  push:
    branches: [ "lab04" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Lab3/590MakefileLab

    steps:
    - uses: actions/checkout@v4
    
    - name: Build program
      run: make

    - name: Run program
      run: make run

    - name: Verify output
      run: |
        output=$(make run)
        echo "$output"
        echo "$output" | grep -q "55"
        echo "$output" | grep -q "1.618034"
